/*
 *  Copyright (C) 2010 Ruben Laguna <ruben.laguna@gmail.com>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.rubenlaguna.en4j.mainmodule;

import ca.odell.glazedlists.BasicEventList;
import ca.odell.glazedlists.EventList;
import ca.odell.glazedlists.FilterList;
import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.gui.TableFormat;
import ca.odell.glazedlists.swing.EventSelectionModel;
import ca.odell.glazedlists.swing.EventTableModel;
import java.beans.PropertyChangeEvent;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLayeredPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import org.openide.util.NbBundle;
import org.openide.util.RequestProcessor.Task;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.Lookup;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import com.rubenlaguna.en4j.interfaces.NoteFinder;
import com.rubenlaguna.en4j.interfaces.NoteRepository;
import com.rubenlaguna.en4j.noteinterface.Note;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import javax.swing.OverlayLayout;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentListener;
import org.openide.util.RequestProcessor;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//com.rubenlaguna.en4j.mainmodule//NoteList//EN",
autostore = false)
public final class NoteListTopComponent extends TopComponent implements ListSelectionListener, PropertyChangeListener {

    private static final Logger LOG = Logger.getLogger(NoteListTopComponent.class.getName());
    private static final RequestProcessor RP = new RequestProcessor("search tasks", 2);
    private static NoteListTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "NoteListTopComponent";
    private final InstanceContent ic = new InstanceContent();
    private RequestProcessor.Task currentSearchTask = null;
    private RequestProcessor.Task currentRefreshTask = null;
    private String searchstring = "";
    private final CustomGlassPane customGlassPane = new CustomGlassPane();
    //empty it will be populated in componentOpened
    private EventList<Note> allNotes = GlazedLists.threadSafeList(new BasicEventList<Note>());
    private NoteMatcherEditor notesMatcher = new NoteMatcherEditor();
    private FilterList<Note> filteredList = new FilterList<Note>(allNotes, notesMatcher);

    private EventSelectionModel selectionModel = null;

    public NoteListTopComponent() {
        LOG.log(Level.INFO, "creating NoteListTopComponen {0}", this.toString());
        initComponents();
        setName(NbBundle.getMessage(NoteListTopComponent.class, "CTL_NoteListTopComponent"));
        setToolTipText(NbBundle.getMessage(NoteListTopComponent.class, "HINT_NoteListTopComponent"));
        associateLookup(new AbstractLookup(ic));
        putClientProperty(PROP_CLOSING_DISABLED, true);
//        jTable1.getSelectionModel().addListSelectionListener(this);
        customGlassPane.setVisible(false);
        jLayeredPane1.add(customGlassPane, (Integer) (JLayeredPane.DEFAULT_LAYER + 50));
    }

    public void refresh() {
        LOG.log(Level.FINE, "refresh notelist {0}", new SimpleDateFormat("h:mm:ss a").format(new Date()));
        performSearch();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane1.setLayout(new OverlayLayout(jLayeredPane1));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchJButton = new javax.swing.JButton();
        partialResultsJLabel = new javax.swing.JLabel();

        jScrollPane1.setBounds(jLayeredPane1.getVisibleRect());

        jTable1.setModel(getGlazedListTableModel());
        jTable1.setBounds(jScrollPane1.getVisibleRect());
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jScrollPane1.setBounds(0, 0, 450, -1);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        searchTextField.setText(org.openide.util.NbBundle.getMessage(NoteListTopComponent.class, "NoteListTopComponent.searchTextField.text")); // NOI18N
        searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusLost(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(searchJButton, org.openide.util.NbBundle.getMessage(NoteListTopComponent.class, "NoteListTopComponent.searchJButton.text")); // NOI18N
        searchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(partialResultsJLabel, org.openide.util.NbBundle.getMessage(NoteListTopComponent.class, "NoteListTopComponent.partialResultsJLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partialResultsJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchJButton)
                    .addComponent(partialResultsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJButtonActionPerformed
        performSearch();
    }//GEN-LAST:event_searchJButtonActionPerformed

    private void performSearch() {
        if (currentSearchTask != null) {
            currentSearchTask.cancel();
        }
        LOG.log(Level.INFO, "{0} searchstring {1}", new Object[]{this.toString(), searchstring});

        Runnable r = new Runnable() {

            @Override
            public void run() {

                final Task dimTask = postDimTask();
                final String text = searchstring;
                LOG.fine("searching in lucene...");
                Collection<Note> prelList = Collections.EMPTY_LIST;
                if (text.trim().isEmpty() || text.equals(org.openide.util.NbBundle.getMessage(NoteListTopComponent.class, "NoteListTopComponent.searchTextField.text"))) {
                    LOG.log(Level.FINE, "no need to search the search box is empty {0} from thread {1}", new Object[]{text, Thread.currentThread().getName()});
                    prelList = getAllNotesInDb();
                } else {
                    NoteFinder finder = Lookup.getDefault().lookup(NoteFinder.class);
                    prelList = finder.find(text);
                    LOG.log(Level.INFO, "search for {0} returned {1} results.", new Object[]{text, prelList.size()});
                }
                LOG.log(Level.INFO, "prelList size {0}", prelList.size());
                notesMatcher.refilter(prelList);
                dimTask.cancel();
                dimTask.waitFinished();
                final int repSize = Lookup.getDefault().lookup(NoteRepository.class).size();
                SwingUtilities.invokeLater(new Runnable() {

                    @Override
                    public void run() {
                        final String text = filteredList.size() + "/" + repSize;
                        LOG.log(Level.INFO, "Refreshing the label in the EDT with {0}", text);
                        partialResultsJLabel.setText(text);
                        customGlassPane.setVisible(false);
                    }
                });
            }

            private Task postDimTask() {
                Runnable dimListRunnable = new Runnable() {

                    @Override
                    public void run() {
                        SwingUtilities.invokeLater(new Runnable() {

                            @Override
                            public void run() {
                                customGlassPane.setVisible(true);
                            }
                        });
                    }
                };
                final Task dimTask = RP.post(dimListRunnable, 500);
                return dimTask;
            }
        };

        currentSearchTask = RP.post(r, 500);
        LOG.fine("currentSearchtask posted");
    }

    private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained
        // TODO add your handling code here:
        String initialText = org.openide.util.NbBundle.getMessage(NoteListTopComponent.class, "NoteListTopComponent.searchTextField.text");
        if (initialText.equals(searchTextField.getText())) {
            searchTextField.setText("");
        }
    }//GEN-LAST:event_searchTextFieldFocusGained

    private void searchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusLost
        // TODO add your handling code here:
        if ("".equals(searchTextField.getText())) {
            LOG.info("searchTextField was empty so reset to the default text");
            searchTextField.setText(org.openide.util.NbBundle.getMessage(NoteListTopComponent.class, "NoteListTopComponent.searchTextField.text"));
        }
    }//GEN-LAST:event_searchTextFieldFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel partialResultsJLabel;
    private javax.swing.JButton searchJButton;
    public final javax.swing.JTextField searchTextField = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables

    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized NoteListTopComponent getDefault() {
        if (instance == null) {
            instance = new NoteListTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the NoteListTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized NoteListTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(NoteListTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof NoteListTopComponent) {
            return (NoteListTopComponent) win;
        }
        Logger.getLogger(NoteListTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    @Override
    public void componentOpened() {
        allNotes.addAll(getAllNotesInDb());
        selectionModel = new EventSelectionModel(filteredList);
        jTable1.setSelectionModel(selectionModel);
        jTable1.getSelectionModel().addListSelectionListener(this);

        NoteRepository rep = Lookup.getDefault().lookup(NoteRepository.class);
        rep.addPropertyChangeListener(this);
        Lookup.getDefault().lookup(NoteFinder.class).addPropertyChangeListener(this);
        LOG.log(Level.INFO, "{0} registered as listener to NoteRepositor and NoteFinder", this.toString());
        searchTextField.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                search();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                search();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                search();
            }

            private void search() {
                searchstring = searchTextField.getText();
                LOG.log(Level.INFO, "searchTextField changed: {0}", searchTextField.getText());
                performSearch();
            }
        });
        performSearch(); // to populate the table
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
        NoteRepository rep = Lookup.getDefault().lookup(NoteRepository.class);
        rep.removePropertyChangeListener(this);
        Lookup.getDefault().lookup(NoteFinder.class).removePropertyChangeListener(this);
        LOG.log(Level.INFO, "{0} removed as listener to NoteRepositor and NoteFinder", this.toString());
    }

    @Override
    protected void componentActivated() {
        searchTextField.requestFocusInWindow();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        NoteListTopComponent singleton = NoteListTopComponent.getDefault();
        singleton.readPropertiesImpl(p);
        return singleton;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    private Collection<Note> getAllNotesInDb() {
        NoteRepository rep = Lookup.getDefault().lookup(NoteRepository.class);
        return rep.getAllNotes();
    }

    @Override
    /**
     * @see         javax.swing.event.ListSelectionListener#valueChanged
     */
    public void valueChanged(ListSelectionEvent arg0) {
            if (!arg0.getValueIsAdjusting()) {
            if (selectionModel != null) {
                EventList<Note> selectionList = selectionModel.getSelected();
                if (!selectionList.isEmpty()) {
                    Object value = selectionList.get(0);
                    LOG.log(Level.FINE, "selection changed: {0}", value.toString());
                    ic.set(Collections.singleton(value), null);
                    return;
                }
            }
            ic.set(Collections.emptySet(), null);
            LOG.log(Level.FINE, "selection changed: nothing selected");
        }
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        LOG.fine("change in noterepository / index");
        if (null != currentRefreshTask) {
            //cancel the last refresh so we only
            //two refresh task at a given moment
            currentRefreshTask.cancel();
        }
        Runnable runnable = new Runnable() {

            @Override
            public void run() {
                NoteListTopComponent.this.refresh();
            }
        };
        currentRefreshTask = RP.post(runnable);
    }

    private TableModel getGlazedListTableModel() {

        String[] propertyNames = {"title"};
        String[] columnLabels = {"Title"};
        TableFormat<Note> tf = GlazedLists.tableFormat(Note.class, propertyNames, columnLabels);
        EventTableModel<Note> etm = new EventTableModel<Note>(filteredList, tf);
        return etm;
    }
}
